// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp556Rf1BMpuX8WD055F3vhGDoM3bxht0',
    appId: '1:197839317602:web:6b6db09fd3abf449187f3b',
    messagingSenderId: '197839317602',
    projectId: 'chefsys-cd440',
    authDomain: 'chefsys-cd440.firebaseapp.com',
    databaseURL: 'https://chefsys-cd440-default-rtdb.firebaseio.com',
    storageBucket: 'chefsys-cd440.appspot.com',
    measurementId: 'G-F344NKTDYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBow0AAX0KM1V71VCYBJgQnkmfdoPwb8c4',
    appId: '1:197839317602:android:113820d44595bea3187f3b',
    messagingSenderId: '197839317602',
    projectId: 'chefsys-cd440',
    databaseURL: 'https://chefsys-cd440-default-rtdb.firebaseio.com',
    storageBucket: 'chefsys-cd440.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClPdhqH1Tn-XB_39bLQgRks_IzloVl2E8',
    appId: '1:197839317602:ios:15e9ce0507271d4d187f3b',
    messagingSenderId: '197839317602',
    projectId: 'chefsys-cd440',
    databaseURL: 'https://chefsys-cd440-default-rtdb.firebaseio.com',
    storageBucket: 'chefsys-cd440.appspot.com',
    iosBundleId: 'com.example.chefsysApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClPdhqH1Tn-XB_39bLQgRks_IzloVl2E8',
    appId: '1:197839317602:ios:6fe6059b5d21836f187f3b',
    messagingSenderId: '197839317602',
    projectId: 'chefsys-cd440',
    databaseURL: 'https://chefsys-cd440-default-rtdb.firebaseio.com',
    storageBucket: 'chefsys-cd440.appspot.com',
    iosBundleId: 'com.example.chefsysApp.RunnerTests',
  );
}
